In [1]:
import torch

class TinyModel(torch.nn.Module):
    
    def __init__(self):
        super(TinyModel, self).__init__()
        
        self.linear1 = torch.nn.Linear(100, 200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200, 10)
        self.softmax = torch.nn.Softmax()
    
    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

tinymodel = TinyModel()

print('The model:')
print(tinymodel)

print('\n\nJust one layer:')
print(tinymodel.linear2)

print('\n\nModel params:')
for param in tinymodel.parameters():
    print(param)

print('\n\nLayer params:')
for param in tinymodel.linear2.parameters():
    print(param)

The model:
TinyModel(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)


Just one layer:
Linear(in_features=200, out_features=10, bias=True)


Model params:
Parameter containing:
tensor([[ 0.0378, -0.0696, -0.0798,  ...,  0.0482,  0.0729,  0.0185],
        [ 0.0557, -0.0059,  0.0873,  ..., -0.0572,  0.0304, -0.0263],
        [-0.0543, -0.0431, -0.0243,  ..., -0.0414, -0.0536,  0.0338],
        ...,
        [ 0.0972,  0.0026,  0.0098,  ..., -0.0662,  0.0016, -0.0164],
        [-0.0277,  0.0203,  0.0720,  ...,  0.0602, -0.0169,  0.0816],
        [-0.0357, -0.0098, -0.0157,  ...,  0.0080, -0.0244,  0.0466]],
       requires_grad=True)
Parameter containing:
tensor([ 6.2517e-02, -1.6021e-02,  7.6172e-02,  8.6833e-02, -7.9680e-02,
        -4.5910e-03, -1.1876e-02, -9.5774e-03, -4.5640e-02, -7.6652e-02,
         8.8484e-02,  3.6813e-02,  3.3939e-02,  3.4076

In [2]:
lin = torch.nn.Linear(3, 2)
x = torch.rand(1, 3)
print('Input:')
print(x)

print('\n\nWeight and Bias parameters:')
for param in lin.parameters():
    print(param)

y = lin(x)
print('\n\nOutput:')
print(y)

Input:
tensor([[0.2974, 0.2991, 0.1098]])


Weight and Bias parameters:
Parameter containing:
tensor([[-0.4483,  0.4878, -0.3032],
        [-0.5177, -0.4403, -0.5045]], requires_grad=True)
Parameter containing:
tensor([0.1047, 0.4450], requires_grad=True)


Output:
tensor([[0.0840, 0.1039]], grad_fn=<AddmmBackward>)


In [3]:
import torch.functional as F


class LeNet(torch.nn.Module):

    def __init__(self):
        super(LeNet, self).__init__()
        # 1 input image channel (black & white), 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = torch.nn.Conv2d(1, 6, 5)
        self.conv2 = torch.nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = torch.nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = torch.nn.Linear(120, 84)
        self.fc3 = torch.nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features