In [1]:
import torch

class TinyModel(torch.nn.Module):
    
    def __init__(self):
        super(TinyModel, self).__init__()
        
        self.linear1 = torch.nn.Linear(100, 200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200, 10)
        self.softmax = torch.nn.Softmax()
    
    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

tinymodel = TinyModel()

print('The model:')
print(tinymodel)

print('\n\nJust one layer:')
print(tinymodel.linear2)

print('\n\nModel params:')
for param in tinymodel.parameters():
    print(param)

print('\n\nLayer params:')
for param in tinymodel.linear2.parameters():
    print(param)

The model:
TinyModel(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)


Just one layer:
Linear(in_features=200, out_features=10, bias=True)


Model params:
Parameter containing:
tensor([[ 0.0378, -0.0696, -0.0798,  ...,  0.0482,  0.0729,  0.0185],
        [ 0.0557, -0.0059,  0.0873,  ..., -0.0572,  0.0304, -0.0263],
        [-0.0543, -0.0431, -0.0243,  ..., -0.0414, -0.0536,  0.0338],
        ...,
        [ 0.0972,  0.0026,  0.0098,  ..., -0.0662,  0.0016, -0.0164],
        [-0.0277,  0.0203,  0.0720,  ...,  0.0602, -0.0169,  0.0816],
        [-0.0357, -0.0098, -0.0157,  ...,  0.0080, -0.0244,  0.0466]],
       requires_grad=True)
Parameter containing:
tensor([ 6.2517e-02, -1.6021e-02,  7.6172e-02,  8.6833e-02, -7.9680e-02,
        -4.5910e-03, -1.1876e-02, -9.5774e-03, -4.5640e-02, -7.6652e-02,
         8.8484e-02,  3.6813e-02,  3.3939e-02,  3.4076

In [2]:
lin = torch.nn.Linear(3, 2)
x = torch.rand(1, 3)
print('Input:')
print(x)

print('\n\nWeight and Bias parameters:')
for param in lin.parameters():
    print(param)

y = lin(x)
print('\n\nOutput:')
print(y)

Input:
tensor([[0.2974, 0.2991, 0.1098]])


Weight and Bias parameters:
Parameter containing:
tensor([[-0.4483,  0.4878, -0.3032],
        [-0.5177, -0.4403, -0.5045]], requires_grad=True)
Parameter containing:
tensor([0.1047, 0.4450], requires_grad=True)


Output:
tensor([[0.0840, 0.1039]], grad_fn=<AddmmBackward>)


In [3]:
import torch.functional as F


class LeNet(torch.nn.Module):

    def __init__(self):
        super(LeNet, self).__init__()
        # 1 input image channel (black & white), 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = torch.nn.Conv2d(1, 6, 5)
        self.conv2 = torch.nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = torch.nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = torch.nn.Linear(120, 84)
        self.fc3 = torch.nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [4]:
class LSTMTagger(torch.nn.Module):

    def __init__(self, embedding_dim, hidden_dim, vocab_size, tagset_size):
        super(LSTMTagger, self).__init__()
        self.hidden_dim = hidden_dim

        self.word_embeddings = torch.nn.Embedding(vocab_size, embedding_dim)

        # The LSTM takes word embeddings as inputs, and outputs hidden states
        # with dimensionality hidden_dim.
        self.lstm = torch.nn.LSTM(embedding_dim, hidden_dim)

        # The linear layer that maps from hidden state space to tag space
        self.hidden2tag = torch.nn.Linear(hidden_dim, tagset_size)

    def forward(self, sentence):
        embeds = self.word_embeddings(sentence)
        lstm_out, _ = self.lstm(embeds.view(len(sentence), 1, -1))
        tag_space = self.hidden2tag(lstm_out.view(len(sentence), -1))
        tag_scores = F.log_softmax(tag_space, dim=1)
        return tag_scores

In [5]:
my_tensor = torch.rand(1, 6, 6)
print(my_tensor)

maxpool_layer = torch.nn.MaxPool2d(3)
print(maxpool_layer(my_tensor))

tensor([[[0.3273, 0.3020, 0.8250, 0.2330, 0.3862, 0.3079],
         [0.7776, 0.0653, 0.2942, 0.4479, 0.5661, 0.2117],
         [0.0745, 0.1371, 0.3072, 0.9823, 0.6118, 0.8466],
         [0.9683, 0.5115, 0.1067, 0.0464, 0.5423, 0.8410],
         [0.8887, 0.2271, 0.6566, 0.6585, 0.1223, 0.2694],
         [0.6266, 0.1700, 0.7565, 0.0117, 0.1690, 0.3281]]])
tensor([[[0.8250, 0.9823],
         [0.9683, 0.8410]]])


C:\Users\DESMOND\anaconda3\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)


In [6]:
my_tensor = torch.rand(1, 4, 4) * 20 + 5
print(my_tensor)

print(my_tensor.mean())

norm_layer = torch.nn.BatchNorm1d(4)
normed_tensor = norm_layer(my_tensor)
print(normed_tensor)

print(normed_tensor.mean())

tensor([[[23.5265, 10.2418, 23.3262, 10.3245],
         [17.8835, 14.2770, 18.1023, 18.6686],
         [12.4849, 23.3658,  6.8811, 19.7874],
         [19.0688, 19.3961, 22.5178, 19.3899]]])
tensor(17.4526)
tensor([[[ 1.0152, -1.0062,  0.9847, -0.9936],
         [ 0.3760, -1.7081,  0.5025,  0.8297],
         [-0.4918,  1.2098, -1.3681,  0.6502],
         [-0.7285, -0.4957,  1.7244, -0.5002]]],
       grad_fn=<NativeBatchNormBackward>)
tensor(1.2666e-07, grad_fn=<MeanBackward0>)


In [7]:
my_tensor = torch.rand(1, 4, 4)

dropout = torch.nn.Dropout(p=0.4)
print(dropout(my_tensor))
print(dropout(my_tensor))

tensor([[[0.0000, 0.0000, 1.5051, 1.5994],
         [0.0000, 0.2814, 0.0000, 0.2457],
         [0.3077, 0.2056, 0.6613, 1.5394],
         [1.4015, 0.0000, 0.3422, 1.5266]]])
tensor([[[1.3286, 0.0000, 1.5051, 0.0000],
         [0.3877, 0.2814, 1.1062, 0.2457],
         [0.0000, 0.0000, 0.6613, 1.5394],
         [1.4015, 1.0666, 0.3422, 1.5266]]])
